parameters: {}
environment:
  POSTGRES_HOST: 
  POSTGRES_PORT:
  POSTGRES_DB:
  POSTGRES_USER: 
  POSTGRES_PASSWORD: 
  POSTGRES_SCHEMA:
  POSTGRES_SSL_CA: 
packages:
    - name: finlog
      shared: false
      functions:
        - name: test
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
