version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
    ports:
      - '5432:5432'
    volumes:
      - ../db/sql:/docker-entrypoint-initdb.d/
