create extension if not exists "uuid-ossp";

create table prod.currencies (
    code varchar(3) primary key,
    name varchar(100) not null,
    flag varchar(4) not null
);

insert into prod.currencies (code, name, flag) VALUES
  ('USD', 'United States Dollar', '🇺🇸'),
  ('EUR', 'Euro', '🇪🇺'),
  ('GBP', 'Pound Sterling', '🇬🇧'),
  ('JPY', 'Japanese Yen', '🇯🇵'),
  ('CHF', 'Swiss Franc', '🇨🇭'),
  ('CAD', 'Canadian Dollar', '🇨🇦'),
  ('AUD', 'Australian Dollar', '🇦🇺'),
  ('NZD', 'New Zealand Dollar', '🇳🇿'),
  ('CNY', 'Chinese Yuan', '🇨🇳'),
  ('HKD', 'Hong Kong Dollar', '🇭🇰'),
  ('SGD', 'Singapore Dollar', '🇸🇬'),
  ('KRW', 'South Korean Won', '🇰🇷'),
  ('INR', 'Indian Rupee', '🇮🇳'),
  ('RUB', 'Russian Ruble', '🇷🇺'),
  ('TRY', 'Turkish Lira', '🇹🇷'),
  ('BRL', 'Brazilian Real', '🇧🇷'),
  ('ZAR', 'South African Rand', '🇿🇦'),
  ('SAR', 'Saudi Riyal', '🇸🇦'),
  ('AED', 'United Arab Emirates Dirham', '🇦🇪'),
  ('AMD', 'Armenian Dram', '🇦🇲'),
  ('KZT', 'Kazakhstani Tenge', '🇰🇿'),
  ('IDR', 'Indonesian Rupiah', '🇮🇩'),
  ('BTC', 'Bitcoin', '🪙');

create table prod.countries (
  id serial primary key,
  name varchar(100) not null,
  flag varchar(4) not null
);

insert into prod.countries (name, flag) values
('Afghanistan', '🇦🇫'),
('Albania', '🇦🇱'),
('Algeria', '🇩🇿'),
('Andorra', '🇦🇩'),
('Angola', '🇦🇴'),
('Antigua and Barbuda', '🇦🇬'),
('Argentina', '🇦🇷'),
('Armenia', '🇦🇲'),
('Australia', '🇦🇺'),
('Austria', '🇦🇹'),
('Azerbaijan', '🇦🇿'),
('Bahamas', '🇧🇸'),
('Bahrain', '🇧🇭'),
('Bangladesh', '🇧🇩'),
('Barbados', '🇧🇧'),
('Belarus', '🇧🇾'),
('Belgium', '🇧🇪'),
('Belize', '🇧🇿'),
('Benin', '🇧🇯'),
('Bhutan', '🇧🇹'),
('Bolivia', '🇧🇴'),
('Bosnia and Herzegovina', '🇧🇦'),
('Botswana', '🇧🇼'),
('Brazil', '🇧🇷'),
('Brunei', '🇧🇳'),
('Bulgaria', '🇧🇬'),
('Burkina Faso', '🇧🇫'),
('Burundi', '🇧🇮'),
('Cabo Verde', '🇨🇻'),
('Cambodia', '🇰🇭'),
('Cameroon', '🇨🇲'),
('Canada', '🇨🇦'),
('Central African Republic', '🇨🇫'),
('Chad', '🇹🇩'),
('Chile', '🇨🇱'),
('China', '🇨🇳'),
('Colombia', '🇨🇴'),
('Comoros', '🇰🇲'),
('Congo', '🇨🇬'),
('Costa Rica', '🇨🇷'),
('Croatia', '🇭🇷'),
('Cuba', '🇨🇺'),
('Cyprus', '🇨🇾'),
('Czechia', '🇨🇿'),
('Denmark', '🇩🇰'),
('Djibouti', '🇩🇯'),
('Dominica', '🇩🇲'),
('Dominican Republic', '🇩🇴'),
('Ecuador', '🇪🇨'),
('Egypt', '🇪🇬'),
('El Salvador', '🇸🇻'),
('Equatorial Guinea', '🇬🇶'),
('Eritrea', '🇪🇷'),
('Estonia', ''),
('Ethiopia', '🇪🇹'),
('Fiji', '🇫🇯'),
('Finland', '🇫🇮'),
('France', '🇫🇷'),
('Gabon', '🇬🇦'),
('Gambia', '🇬🇲'),
('Georgia', '🇬🇪'),
('Germany', '🇩🇪'),
('Ghana', '🇬🇭'),
('Greece', '🇬🇷'),
('Grenada', '🇬🇩'),
('Guatemala', '🇬🇹'),
('Guinea', '🇬🇳'),
('Guinea-Bissau', '🇬🇼'),
('Guyana', '🇬🇾'),
('Haiti', '🇭🇹'),
('Honduras', '🇭🇳'),
('Hungary', '🇭🇺'),
('Iceland', '🇮🇸'),
('India', '🇮🇳'),
('Indonesia', '🇮🇩'),
('Iran', '🇮🇷'),
('Iraq', '🇮🇶'),
('Ireland', '🇮🇪'),
('Israel', '🇮🇱'),
('Italy', '🇮🇹'),
('Jamaica', '🇯🇲'),
('Japan', '🇯🇵'),
('Jordan', '🇯🇴'),
('Kazakhstan', '🇰🇿'),
('Kenya', '🇰🇪'),
('Kiribati', '🇰🇮'),
('Kuwait', '🇰🇼'),
('Kyrgyzstan', '🇰🇬'),
('Laos', '🇱🇦'),
('Latvia', '🇱🇻'),
('Lebanon', '🇱🇧'),
('Lesotho', '🇱🇸'),
('Liberia', '🇱🇷'),
('Libya', '🇱🇾'),
('Liechtenstein', '🇱🇮'),
('Lithuania', '🇱🇹'),
('Luxembourg', '🇱🇺'),
('Madagascar', '🇲🇬'),
('Malawi', '🇲🇼'),
('Malaysia', '🇲🇾'),
('Maldives', '🇲🇻'),
('Mali', '🇲🇱'),
('Malta', '🇲🇹'),
('Marshall Islands', '🇲🇭'),
('Mauritania', '🇲🇷'),
('Mauritius', '🇲🇺'),
('Mexico', '🇲🇽'),
('Micronesia', '🇫🇲'),
('Moldova', '🇲🇩'),
('Monaco', '🇲🇨'),
('Mongolia', '🇲🇳'),
('Montenegro', '🇲🇪'),
('Morocco', '🇲🇦'),
('Mozambique', '🇲🇿'),
('Namibia', '🇳🇦'),
('Nauru', '🇳🇷'),
('Nepal', '🇳🇵'),
('Netherlands', '🇳🇱'),
('New Zealand', '🇳🇿'),
('Nicaragua', '🇳🇮'),
('Niger', '🇳🇪'),
('Nigeria', '🇳🇬'),
('North Korea', '🇰🇵'),
('North Macedonia', '🇲🇰'),
('Norway', '🇳🇴'),
('Oman', '🇴🇲'),
('Pakistan', '🇵🇰'),
('Palau', '🇵🇼'),
('Panama', '🇵🇦'),
('Papua New Guinea', '🇵🇬'),
('Paraguay', '🇵🇾'),
('Peru', '🇵🇪'),
('Philippines', '🇵🇭'),
('Poland', '🇵🇱'),
('Portugal', '🇵🇹'),
('Qatar', '🇶🇦'),
('Romania', '🇷🇴'),
('Russia', '🇷🇺'),
('Rwanda', '🇷🇼'),
('Saint Kitts and Nevis', '🇰🇳'),
('Saint Lucia', '🇱🇨'),
('Saint Vincent and the Grenadines', '🇻🇨'),
('Samoa', '🇼🇸'),
('San Marino', '🇸🇲'),
('Sao Tome and Principe', '🇸🇹'),
('Saudi Arabia', '🇸🇦'),
('Senegal', '🇸🇳'),
('Serbia', '🇷🇸'),
('Seychelles', '🇸🇨'),
('Sierra Leone', '🇸🇱'),
('Singapore', '🇸🇬'),
('Slovakia', '🇸🇰'),
('Slovenia', '🇸🇮'),
('Solomon Islands', '🇸🇧'),
('Somalia', '🇸🇴'),
('South Africa', '🇿🇦'),
('South Korea', '🇰🇷'),
('South Sudan', '🇸🇸'),
('Spain', '🇪🇸'),
('Sri Lanka', '🇱🇰'),
('Sudan', '🇸🇩'),
('Suriname', '🇸🇷'),
('Sweden', '🇸🇪'),
('Switzerland', '🇨🇭'),
('Syria', '🇸🇾'),
('Taiwan', '🇹🇼'),
('Tajikistan', '🇹🇯'),
('Tanzania', '🇹🇿'),
('Thailand', '🇹🇭'),
('Timor-Leste', '🇹🇱'),
('Togo', '🇹🇬'),
('Tonga', '🇹🇴'),
('Trinidad and Tobago', '🇹🇹'),
('Tunisia', '🇹🇳'),
('Turkey', '🇹🇷'),
('Turkmenistan', '🇹🇲'),
('Tuvalu', '🇹🇻'),
('Uganda', '🇺🇬'),
('Ukraine', '🇺🇦'),
('United Arab Emirates', '🇦🇪'),
('United Kingdom', '🇬🇧'),
('United States', '🇺🇸'),
('Uruguay', '🇺🇾'),
('Uzbekistan', '🇺🇿'),
('Vanuatu', '🇻🇺'),
('Vatican City', '🇻🇦'),
('Venezuela', '🇻🇪'),
('Vietnam', '🇻🇳'),
('Yemen', '🇾🇪'),
('Zambia', '🇿🇲'),
('Zimbabwe', '🇿🇼'),
('None', '🌎');

create table prod.currency_rates (
  id serial primary key,
  from_currency varchar(3) not null,
  to_currency varchar(3) not null,
  date timestamp not null,
  value numeric(20, 10) not null,
  source varchar(50) not null
);
create index idx_currency_rates_from_to ON prod.currency_rates (from_currency, to_currency);

create table prod.operation_categories (
  id serial primary key,
  name varchar(100) not null unique,
  description varchar(100) not null default ''
);

insert into prod.operation_categories (name) values
('💰 Разное'),
('🥦 Питание'),
('🚗 Машина'),
('👾 Развлечения'),
('📱 Подписки'),
('🏡 Квартира'),
('✈️ Путешествия'),
('💊 Лечение'),
('💄 Косметика'),
('🏀 Спорт'),
('🍽️ Рестораны'),
('👕 Одежда'),
('🚕 Транспорт'),
('🎁 Подарки'),
('📆 Разное регулярное'),
('💻 Техника'),
('🏧 Cнятие наличных'),
('💸 Комиссии'),
('💸 Потери'),
('💼 Зарплата'),
('💼 Долги'),
('💼 Наличные'),
('💼 Разовые выплаты'),
('🏦 Проценты'),
('🏁 Начальная сумма'),
('👫 Между собой'),
('🇰🇿 В Казахстан'),
('🔮 В накопления'),
('💱 Конвертация');

create table prod.account_categories (
  code varchar(20) primary key,
  name varchar(100) not null unique,
  description varchar(200) not null default ''
);

insert into prod.account_categories (code, name, description) values
('current', 'Текущий', 'Для ежедневных трат'),
('savings', 'Накопления', 'Счета, с которых не тратим'),
('unavailable', 'Недоступно', 'Долги, заблокированные, зависшие средства');

create table prod.users (
  id serial primary key,
  name varchar(100) not null unique,
  full_name varchar(100) not null
);

create table prod.accounts(
  id serial primary key,
  name varchar(100) not null unique,
  currency varchar(3) not null references prod.currencies (code),
  category varchar(20) not null references prod.account_categories (code),
  country_id integer not null references prod.countries (id),
  owner_id integer not null references prod.users (id),
  comment varchar(200) not null default '',
  created_at timestamp not null default now()
);

create type transaction_type as enum ('spending', 'income', 'movement');

create table prod.operations(
  id serial primary key,
  tx_id uuid not null default uuid_generate_v4(),
  tx_seq integer not null default 1,
  tx_type transaction_type not null,
  date timestamp not null,
  amount numeric(20, 10) not null,
  currency varchar(3) not null references prod.currencies (code),
  account_id integer not null references prod.accounts (id),
  exchange_rate numeric(20, 10) not null,
  category_id integer not null references prod.operation_categories (id),
  comment varchar(200) not null default '',
  created_at timestamp not null default now()
);

